# General Jekyll Config
highlighter: rouge
url: https://takagotch.github.io/page35
# baseurl: https://takagotch.github.io/page35
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]



